FROM node:alpine

WORKDIR /app

COPY package.json /app/package.json
COPY index.html /app/index.html
COPY postcss.config.cjs /app/postcss.config.cjs
COPY rescript.json /app/rescript.json
COPY tailwind.config.cjs /app/tailwind.config.cjs
COPY vite.config.js /app/vite.config.js
COPY src /app/src/
COPY entry-point.sh /usr/local/bin/entry-point.sh

RUN chmod +x /usr/local/bin/entry-point.sh
RUN npm install
RUN npm run res:dev

EXPOSE 3000

ENTRYPOINT ["sh", "/usr/local/bin/entry-point.sh"]