// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("div", {
                                  children: "Умные панели",
                                  className: "border-end fw-bold text-indigo-600 p-2"
                                }),
                            className: "col-12 d-flex align-items-center"
                          }),
                      className: "row pt-1 pb-1"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("i", {
                                          className: "fa-solid fa-file-zipper me-2"
                                        }),
                                    "Сборки"
                                  ],
                                  className: "fw-bold"
                                }),
                            className: "col-12 d-flex align-items-center"
                          }),
                      className: "row border-bottom pt-3 pb-3"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("h1", {
                                  children: "Заголовок"
                                }),
                            className: "col-12"
                          }),
                      className: "row mt-5"
                    })
              ],
              className: "container-fluid"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
