// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Умные панели",
                                      className: "text-capitalize border-end fw-bold text-indigo-600 pe-2 me-3"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("i", {
                                                    className: "fa-solid fa-table-list",
                                                    style: {
                                                      color: "#5e5c64"
                                                    }
                                                  }),
                                              JsxRuntime.jsx("span", {
                                                    children: "Список",
                                                    className: "me-2 ms-2"
                                                  }),
                                              JsxRuntime.jsx("i", {
                                                    className: "fa-solid fa-caret-down"
                                                  })
                                            ],
                                            className: "d-flex align-items-center bg-white p-2 border rounded"
                                          }),
                                      className: "fw-bold pe-2"
                                    })
                              ],
                              className: "col-6 d-flex align-items-center"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("i", {
                                              className: "fa-solid fa-gear me-3",
                                              style: {
                                                color: "#5e5c64"
                                              }
                                            }),
                                        JsxRuntime.jsx("i", {
                                              className: "fa-solid fa-bell",
                                              style: {
                                                color: "#5e5c64"
                                              }
                                            })
                                      ],
                                      className: "fw-bold pe-2 border-end me-3"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsxs("div", {
                                                  children: [
                                                    JsxRuntime.jsx("i", {
                                                          className: "fa-regular fa-user",
                                                          style: {
                                                            color: "#5e5c64"
                                                          }
                                                        }),
                                                    JsxRuntime.jsx("span", {
                                                          children: "Имя пользователя",
                                                          className: "me-2 ms-2"
                                                        }),
                                                    JsxRuntime.jsx("i", {
                                                          className: "fa-solid fa-caret-down"
                                                        })
                                                  ],
                                                  className: "d-flex align-items-center bg-white p-2 border rounded"
                                                }),
                                            className: "fw-bold pe-2"
                                          }),
                                      className: "fw-bold pe-2"
                                    })
                              ],
                              className: "col-6 d-flex align-items-center justify-content-end"
                            })
                      ],
                      className: "row pt-1 pb-1"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "fa-regular fa-images me-2"
                                          }),
                                      "Галерея"
                                    ],
                                    className: "fw-bold me-4"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "fa-solid fa-circle-play me-2"
                                          }),
                                      "Контент"
                                    ],
                                    className: "fw-bold me-4"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "fa-solid fa-tv me-2"
                                          }),
                                      "Устройства"
                                    ],
                                    className: "fw-bold me-4"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "fa-solid fa-object-group me-2"
                                          }),
                                      "Группы устройств"
                                    ],
                                    className: "fw-bold me-4"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "fa-solid fa-file-video me-2"
                                          }),
                                      "Плэйлисты"
                                    ],
                                    className: "fw-bold me-4"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("i", {
                                            className: "fa-solid fa-list-check me-2"
                                          }),
                                      "Задания"
                                    ],
                                    className: "fw-bold"
                                  })
                            ],
                            className: "col-12 d-flex align-items-center"
                          }),
                      className: "row border-bottom pt-3 pb-3"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("div", {
                                  children: "Заголовок",
                                  className: "fw-bold fs-5"
                                }),
                            className: "col-12"
                          }),
                      className: "row mt-5"
                    })
              ],
              className: "container-fluid"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
